version: '3'
services: 
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    container_name: sequelize-course-db
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports: 
      - ${DB_PORT}
